server:
  port: 8080
  servlet:
    context-path: /api
spring:
  application:
    name: Socia
  threads:
    virtual:
      enabled: true
  datasource:
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-timeout: 2000
      validation-timeout: 5000
      leak-detection-threshold: 60000
      auto-commit: false
      pool-name: master
  transaction:
    default-timeout: 30
  flyway:
    enabled: true
    baseline-version: 1.0.0.0
    baseline-on-migrate: true
    validate-on-migrate: true
    fail-on-missing-locations: true
    table: flyway_schema_history
    locations: classpath:db/migration
  jooq:
    sql-dialect: postgres

logging:
  level:
    org.jooq.Constants: WARN

socia:
  assistant:
    gemini:
      project-id: ${GEMINI_PROJECT_ID:zydon-platform}
      location: ${GEMINI_LOCATION:us-central1}
      credentials: ${GOOGLE_GEMINI_CREDENTIALS:ewogICJ0eXBlIjogInNlcnZpY2VfYWNjb3VudCIsCiAgInByb2plY3RfaWQiOiAienlkb24tcGxhdGZvcm0iLAogICJwcml2YXRlX2tleV9pZCI6ICJmNTA2NGI2N2JkNjhiY2VjZGRlYjcxMDBmZWM1MmIxODU2OWVkMmYzIiwKICAicHJpdmF0ZV9rZXkiOiAiLS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tXG5NSUlFdkFJQkFEQU5CZ2txaGtpRzl3MEJBUUVGQUFTQ0JLWXdnZ1NpQWdFQUFvSUJBUUM1VFVRU21acjhnUUtqXG41RnFpbjVrQWZvMU9nTFEzZ0lGbEN5dXFPRWdNMzIwbVNWcEN5MnVYYjNTWVhNeVJudkRaUWNoSzNGUlFndVRFXG5UQy91Wk9QaUJ1ZzRhTSt5S2FFWFF3T3BFcEdRVzJtckZUQ2hsOGtIYzVRaWsyeGx3V1V6WlpJalVrMVM0eGlIXG5kalFJbnJwR2xoSFE1cVhLQ25LeDIrcmJPUUVwZHpBaHZsRDFCcm16SFpqbjBHVlVxZEFKWGkyaW9WcXh0SkJkXG5ZOTMzWTdhTFZsK1YyaXk4aG9mMWhldDVUbUJRWXhxaER5TldMemczQ2JJUWJOWVdyZmpoallUR3ZJWFROUVVrXG5LSVpYUTlOdXoyRmVaS0FyM1lzRWM1NVg0TXlWT3VZN2Y5ZHArZGp6aFNpZHNPZXk1UTdmUkd5M2d6ZndPMUtjXG4rRWxvN2JhRkFnTUJBQUVDZ2dFQVFnWmhiSDAxNTZXeVFxSnhsd05sK1hLZU4rd05DcitybTB6RkpMUkVHKzRhXG5UcXVSVVQ1NUdpN1k3UmNYdndWU2pSN3UxcG0ySXkvWWdvY2hCd0VFMzdzVlVGQXNQUyt2R2dKRFVpRnZJM0FtXG44Ukl1VDAydGtBMmpLVVM5T1c2VStDREhWdldTM3FkVFRLVVYra0pRWGlsSHROY1NHTERyV0N0amZmUk1VVER0XG53VGNzS0RRZ01oQmRPdWdQUStlZTR6RHJGMm5sc2J3RFB5SkZoakR0NEhuZXo0NlMyOEVjRmY4d3h5NWFxNEVNXG5XV0JNN01sMlB0dXduZnlXZytyZi9VdCt0b1dkZGswUkRPYVpPejZFbnE0RjhRdVlqaUxrM0FreDR6dTBSaEE4XG5BUHNzS053bTllV0VuL3hLOGpZNVFGVHVJT0l2U1gydDhpRmdvYm8reXdLQmdRRDN4QnYyWGFLNm5ReVZoQUsxXG4wQTNmaFZpYWNOOUJGbCtab1NuZzNpTU1XYlVoVWlYOW41Zmhqc0c3ZHI1STlBdVpkY1dLTTdPUU80QWJWZnU4XG5QOFA4ZCsyd1JxRUVzR1YyeDBOYmdMU2tTWkZxT3FsSU5hd0xkeW1zcFlBNTJ3bG9aSm5xaW9EOGRuTm9PYU9yXG5BWDNlT2ZKamZhTi9PYWNrZUF1T1FJNGIxd0tCZ1FDL2RieW1WMEVzaFJONG44TUhIZzF5TkF5eW9IZVVIWnR1XG4rWU90ODlObkE2amtaWjVyQ3lhWWJDM1NyY2VsdUkzRndsNzNrQWZ1ZUhBN1hKSGRENmk5eVFNOGJFaHVPRzNsXG5FWm16NjN3WUFaRTE5akVJM2dycmZPTkVPZXA4ZkhTcEZJajY5eU00bS9VZ2pxcFdDZ1VQd3hEM1dtVzY1ZnVWXG5QR01qYjROVkF3S0JnRS9xeHFZeHo3Sm53ODVhVlZGMXVYUFduQnk4dVpaUjlDWW1zTTVpZUdXY2JldEFoeGFHXG5xc1BMZXp2UGNsTXZ2S29VTGRLRkdLODJNZjBmUCtLWm9zckZtRHBhbmNkWWFuSGtsaHBtcWwydmlTTDlwdXF1XG52VDY1Z2d5NUdXSVAvN25YY1RvUTBNZ2VJTjJHY2Y5UHJOeklUaUcvUGNSa3dUL25KTHNPb1lmakFvR0FVMUdCXG5UMElaY3E1VzB0OXpsOTFVTEtiSi85SWxONmZLeEhpQS9XcG1UU1lpa1lKSGRuM2J4ZWtONStrSVFPNFhoRUFaXG40OUlpSVh6NEdsMG1mUFVia2J1d1ZOTXFrZ3lzaGtzcWdFbXlMeUEvZVNReUlwRytYc3h5ZW5aWnZPTE1RZWhWXG4xQ0ZJaXBJVUVwOERNWDRheGNrMTBPN2Q1bisvQkNyTFdkaGxadEVDZ1lBenFoQ3lNemdzSS9rMW9NYzhIaktMXG5TcmZTQXMvbzJqM0U5dWRpTms3cDRXTHFjQjErSGZaTERaMk4veS9RbFE3bkFlMy9aNmk2SkF4YXdBdjFzbFB5XG5ZazBtZHNDa1R0MFV0QXZhSHhSSTBHK0t4V3FiekZ1RXpPSEVTZVBWVDVGWDQ5dkd1bUlPVXA0QjM4TmNSdHNqXG5CRkxzNzRpVUNOdFVnL1FqOW9pakdBPT1cbi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS1cbiIsCiAgImNsaWVudF9lbWFpbCI6ICJ6b2UtdmVydGV4QHp5ZG9uLXBsYXRmb3JtLmlhbS5nc2VydmljZWFjY291bnQuY29tIiwKICAiY2xpZW50X2lkIjogIjExMTg2NTExMjA4NjAzMzkwOTU1NSIsCiAgImF1dGhfdXJpIjogImh0dHBzOi8vYWNjb3VudHMuZ29vZ2xlLmNvbS9vL29hdXRoMi9hdXRoIiwKICAidG9rZW5fdXJpIjogImh0dHBzOi8vb2F1dGgyLmdvb2dsZWFwaXMuY29tL3Rva2VuIiwKICAiYXV0aF9wcm92aWRlcl94NTA5X2NlcnRfdXJsIjogImh0dHBzOi8vd3d3Lmdvb2dsZWFwaXMuY29tL29hdXRoMi92MS9jZXJ0cyIsCiAgImNsaWVudF94NTA5X2NlcnRfdXJsIjogImh0dHBzOi8vd3d3Lmdvb2dsZWFwaXMuY29tL3JvYm90L3YxL21ldGFkYXRhL3g1MDkvem9lLXZlcnRleCU0MHp5ZG9uLXBsYXRmb3JtLmlhbS5nc2VydmljZWFjY291bnQuY29tIiwKICAidW5pdmVyc2VfZG9tYWluIjogImdvb2dsZWFwaXMuY29tIgp9Cg==}
      timeout-minutes: ${GEMINI_TIMEOUT_MINUTES:5}
      max-retry-attempts: ${GEMINI_MAX_RETRY_ATTEMPTS:5}
      max-retry-delay-seconds: ${GEMINI_MAX_RETRY_DELAY_SECONDS:60}