server:
  port: 8080
  servlet:
    context-path: /api
spring:
  application:
    name: Socia
  threads:
    virtual:
      enabled: true
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/mydatabase}
    username: ${SPRING_DATASOURCE_USERNAME:myuser}
    password: ${SPRING_DATASOURCE_PASSWORD:secret}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-timeout: 2000
      validation-timeout: 5000
      leak-detection-threshold: 60000
      auto-commit: false
      pool-name: master
  transaction:
    default-timeout: 30
  flyway:
    enabled: true
    baseline-version: 1.0.0.0
    baseline-on-migrate: true
    validate-on-migrate: true
    fail-on-missing-locations: true
    table: flyway_schema_history
    locations: classpath:db/migration
  jooq:
    sql-dialect: postgres

logging:
  level:
    br.com.iolab.socia: DEBUG
    org.jooq.Constants: WARN
    com.google.genai: DEBUG
    com.google.auth: DEBUG

socia:
  assistant:
    gemini:
      project-id: ${GEMINI_PROJECT_ID:zydon-platform}
      location: ${GEMINI_LOCATION:us-central1}
      credentials: ${GOOGLE_GEMINI_CREDENTIALS}
      timeout-minutes: ${GEMINI_TIMEOUT_MINUTES:5}
      max-retry-attempts: ${GEMINI_MAX_RETRY_ATTEMPTS:5}
      max-retry-delay-seconds: ${GEMINI_MAX_RETRY_DELAY_SECONDS:60}
  whatsapp:
    client:
      api-url: http://localhost:8081